"""
4eyes.ai — AI-Powered Business Contract Reviewer
Phase 1: CLI Script
Author: Built by Claude for orphic18-bit
Model: GPT-4o-mini | Temp: 0.1
"""

import os
import sys
from openai import OpenAI

# ─────────────────────────────────────────────
# CONFIGURATION
# ─────────────────────────────────────────────

MODEL = "gpt-4o-mini"
TEMPERATURE = 0.1          # Low temp = consistent, predictable output (critical for legal)
MIN_WORD_COUNT = 80        # Contracts shorter than this are probably not contracts
MAX_TOKENS = 2500          # Enough for a full structured analysis

# ─────────────────────────────────────────────
# SYSTEM PROMPT — The brain of 4eyes.ai
# ─────────────────────────────────────────────

SYSTEM_PROMPT = """
You are 4eyes.ai, a calm and highly experienced business contract analyst.
Your job is to review business contracts on behalf of solo founders and small SaaS teams
and return a clear, structured analysis in plain English.

TONE RULES:
- Be calm, direct, and non-alarmist.
- Do not sensationalize risks. If a clause is standard and common, say so.
- Do not give specific legal advice. You are a reviewer, not a lawyer.
- If a clause is genuinely ambiguous or its interpretation depends on jurisdiction,
  say so explicitly and recommend consulting a qualified lawyer.
- Flag genuine red flags clearly, but only when they are actually risky.

OUTPUT FORMAT:
Always respond using EXACTLY this structure, with the section headers as written:

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
4eyes.ai — CONTRACT ANALYSIS REPORT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📄 CONTRACT TYPE
[Identify the type: NDA, SOW, MSA, Freelance Agreement, SaaS Vendor Agreement, etc.]

👥 KEY PARTIES & OBLIGATIONS
[List the parties involved and summarize what each is obligated to do.]

✅ FAVORABLE CLAUSES
[List clauses that are clearly beneficial or protective for the user. If none, say "None identified."]

⚠️ UNFAVORABLE CLAUSES
[List clauses that disadvantage the user. For each, briefly explain why. If none, say "None identified."]

🚨 RED FLAGS
[List anything that requires immediate attention — unusual, one-sided, or potentially harmful clauses.
 If none, say "No red flags identified."]

❓ MISSING CLAUSES
[List important clauses that are absent but should be present in this type of contract.
 If nothing significant is missing, say so.]

💬 NEGOTIATION SUGGESTIONS
[Specific, actionable things the user could push back on or request changes to.]

🏁 OVERALL VERDICT
[One of three options: SIGN / NEGOTIATE / AVOID]
[Follow with 2–3 sentences explaining the verdict plainly.]

─────────────────────────────────────────
⚖️  DISCLAIMER
This analysis is generated by an AI tool and is for informational purposes only.
It does not constitute legal advice. For any contract with significant financial,
legal, or business implications, please consult a qualified attorney.
─────────────────────────────────────────
"""

# ─────────────────────────────────────────────
# INPUT VALIDATOR
# ─────────────────────────────────────────────

def looks_like_a_contract(text: str) -> tuple[bool, str]:
    """
    Basic heuristic check before sending to the API.
    Saves API cost and avoids hallucinated analysis on garbage input.
    Returns (is_valid: bool, reason: str)
    """
    word_count = len(text.split())

    if word_count < MIN_WORD_COUNT:
        return False, (
            f"Input is too short ({word_count} words). "
            f"A contract typically has at least {MIN_WORD_COUNT} words. "
            "Please paste the full contract text."
        )

    # Look for at least a few contract-like signals
    contract_signals = [
        "agree", "agreement", "party", "parties", "shall", "obligations",
        "terms", "conditions", "signed", "signature", "effective date",
        "clause", "section", "whereas", "herein", "payment", "terminate",
        "confidential", "liability", "indemnif", "warranty", "govern"
    ]

    text_lower = text.lower()
    matched = sum(1 for signal in contract_signals if signal in text_lower)

    if matched < 3:
        return False, (
            "This doesn't appear to be a business contract. "
            "4eyes.ai is designed to review contracts like NDAs, SOWs, MSAs, "
            "freelance agreements, or SaaS vendor agreements. "
            "Please paste the actual contract text."
        )

    return True, "ok"


# ─────────────────────────────────────────────
# CORE ANALYSIS FUNCTION
# ─────────────────────────────────────────────

def analyze_contract(contract_text: str) -> str:
    """
    Sends the contract to OpenAI and returns the structured analysis.
    """
    # Pull API key from environment variable (never hardcode keys)
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        print("\n❌  ERROR: OPENAI_API_KEY environment variable not found.")
        print("    Set it with:  set OPENAI_API_KEY=your-key-here  (Windows CMD)")
        print("    Or in PowerShell: $env:OPENAI_API_KEY='your-key-here'")
        sys.exit(1)

    client = OpenAI(api_key=api_key)

    print("\n⏳  Analyzing contract... this usually takes 10–20 seconds.\n")

    try:
        response = client.chat.completions.create(
            model=MODEL,
            temperature=TEMPERATURE,
            max_tokens=MAX_TOKENS,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user",   "content": f"Please review this contract:\n\n{contract_text}"}
            ]
        )
        return response.choices[0].message.content

    except Exception as e:
        return f"\n❌  API Error: {str(e)}\n\nCheck your API key and internet connection."


# ─────────────────────────────────────────────
# INPUT COLLECTION
# ─────────────────────────────────────────────

def collect_contract_input() -> str:
    """
    Prompts the user to paste their contract text.
    They type END on its own line to finish.
    """
    print("━" * 48)
    print("  4eyes.ai — Business Contract Reviewer")
    print("  Phase 1 | Powered by GPT-4o-mini")
    print("━" * 48)
    print()
    print("Paste your contract text below.")
    print("When you're done, type  END  on a new line and press Enter.")
    print()
    print("─" * 48)

    lines = []
    while True:
        try:
            line = input()
            if line.strip().upper() == "END":
                break
            lines.append(line)
        except EOFError:
            # Handles piped input (e.g. python contract_analyzer.py < contract.txt)
            break

    return "\n".join(lines).strip()


# ─────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────

def main():
    contract_text = collect_contract_input()

    if not contract_text:
        print("\n⚠️  No input received. Please paste contract text when prompted.\n")
        sys.exit(0)

    # Validate before hitting the API
    is_valid, reason = looks_like_a_contract(contract_text)
    if not is_valid:
        print(f"\n⚠️  {reason}\n")
        sys.exit(0)

    # Run analysis
    result = analyze_contract(contract_text)

    # Print result
    print("\n" + result + "\n")


if __name__ == "__main__":
    main()
